### ISSUE TITLE
Create a python code for this project

### ISSUE THREAD

**Issue by al-sapsan** [al-sapsan/skill-docker#3]
Бла-бла-бла. Это крутой проект. А это крутое описание крутизны крутого проекта.

**Comment by al-sapsan** [comment]
ok

**Comment by al-sapsan** [comment]
Вижу пулл-реквест.

**Comment by al-sapsan** [comment]
Пояснение кода:
Загрузка изображения: Сначала изображение загружается с использованием функции Image.open.
Изменение размера: В функции resize_image сохраняется соотношение сторон изображения, чтобы избежать искажений.
Преобразование в оттенки серого: Функция grayscale_image конвертирует изображение в черно-белый формат (градации серого).
Сопоставление пикселей: В функции pixels_to_ascii каждый пиксель переводится в символ ASCII в зависимости от его яркости. Чем ярче пиксель, тем "легче" символ (например, "."), и наоборот.
Формирование строк: Затем создается итоговый ASCII-арт, который состоит из строк символов.
Этот код преобразует любое изображение в ASCII-арт, сохраняя его пропорции и используя символы для представления яркости каждого пикселя.

Объяснение кода:
Импорт библиотек: Мы используем PIL для работы с изображениями.
Определение символов ASCII: Задаем набор символов для отображения на основе яркости пикселей.
Функции:
resize_image: Изменяет размер изображения с учетом соотношения сторон.
grayify: Преобразует цветное изображение в градации серого.
pixels_to_ascii: Преобразует яркость пикселей в соответствующие символы ASCII.
convert_image_to_ascii: Основная функция, которая объединяет все шаги.
Вывод результата: ASCII-арт выводится в консоль и сохраняется в текстовый файл.
Этот код позволяет вам преобразовать любое изображение в ASCII-арт и сохранить его для дальнейшего использования.

Дополнительные улучшения:
Выбор палитры символов: Экспериментируйте с различными наборами символов для достижения желаемого эффекта.
Инверсия цветов: Для создания негативного изображения поменяйте порядок символов в списке.
Добавление цвета: Используйте ANSI escape-коды для добавления цвета к ASCII-арту.
Сохранение в различных форматах: Сохраняйте результат в текстовых файлах с разными кодировками или в HTML-файлах.
Примечание:

Качество полученного ASCII-арта зависит от исходного изображения, выбранных символов и масштаба.
Для более сложных преобразований можно использовать библиотеки машинного обучения для выделения контуров или текстур.

**Comment by git-tester2** [comment]
Всё сделано, шеф! :-)

**Comment by al-sapsan** [comment]
Сейчас посмотрю и проверю

**Comment by al-sapsan** [comment]
Настраиваю  GitHub Actions и Dependabot

**Comment by al-sapsan** [comment]
Надо переделать комментарии на английский, VIM матерится.

**Comment by git-tester2** [comment]
Всё сделано, шеф! :-)

**Comment by al-sapsan** [comment]
Пуллреквесть
